-- Lookup table for 16-bit BLE service UUIDs. Mirrors
-- internal/services/uuid_names.go so older captures (taken before the
-- services package learned a UUID's name) still get the right label.
--
-- Sourced from the Bluetooth SIG assigned-numbers list and well-known
-- vendor allocations. Kept manually in sync; update both files together.

CREATE OR REPLACE VIEW service_uuid_names AS
SELECT * FROM (VALUES
    -- Generic GATT
    ('1800', 'Generic Access'),
    ('1801', 'Generic Attribute'),
    ('1802', 'Immediate Alert'),
    ('1803', 'Link Loss'),
    ('1804', 'Tx Power'),
    ('1805', 'Current Time'),
    ('1808', 'Glucose'),
    ('1809', 'Health Thermometer'),
    ('180a', 'Device Information'),
    ('180d', 'Heart Rate'),
    ('180e', 'Phone Alert Status'),
    ('180f', 'Battery'),
    ('1810', 'Blood Pressure'),
    ('1811', 'Alert Notification'),
    ('1812', 'Human Interface Device'),
    ('1813', 'Scan Parameters'),
    ('1814', 'Running Speed and Cadence'),
    ('1815', 'Automation IO'),
    ('1816', 'Cycling Speed and Cadence'),
    ('1818', 'Cycling Power'),
    ('1819', 'Location and Navigation'),
    ('181a', 'Environmental Sensing'),
    ('181b', 'Body Composition'),
    ('181c', 'User Data'),
    ('181d', 'Weight Scale'),
    ('181e', 'Bond Management'),
    ('181f', 'Continuous Glucose Monitoring'),
    ('1820', 'Internet Protocol Support'),
    ('1821', 'Indoor Positioning'),
    ('1822', 'Pulse Oximeter'),
    ('1823', 'HTTP Proxy'),
    ('1824', 'Transport Discovery'),
    ('1825', 'Object Transfer'),
    ('1826', 'Fitness Machine'),
    ('1827', 'Mesh Provisioning'),
    ('1828', 'Mesh Proxy'),
    ('1829', 'Reconnection Configuration'),

    -- Vendor-allocated
    ('fcb6', 'Apple, Inc.'),
    ('fcc6', 'Wiliot LTD'),
    ('fcd2', 'Sony Group Corp.'),
    ('fcef', 'Logitech International SA'),
    ('fcf1', 'Google LLC'),
    ('fd03', 'Garmin International, Inc.'),
    ('fd44', 'Apple, Inc.'),
    ('fd49', 'Microsoft Corporation'),
    ('fd4a', 'Tesla, Inc.'),
    ('fd50', 'Hangzhou Tuya Information Technology Co., Ltd.'),
    ('fd5a', 'Microsoft Swift Pair'),
    ('fd69', 'Samsung Electronics Co., Ltd.'),
    ('fd6f', 'Google Exposure Notification'),
    ('fd72', 'Google Find My Device'),
    ('fd83', 'GoPro, Inc.'),
    ('fd87', 'Samsung Electronics Co., Ltd.'),
    ('fd8f', 'Garmin International, Inc.'),
    ('fda0', 'Apple, Inc.'),
    ('fdab', 'Sony Group Corp.'),
    ('fdb2', 'Tesla, Inc.'),
    ('fdcd', 'Quzhao Tech Co., Ltd.'),
    ('fdd0', 'Huami (Shanghai) Culture Communication Co., Ltd'),
    ('fdda', 'Samsung Galaxy Watch'),
    ('fded', 'Sony Group Corp.'),
    ('fdee', 'Bose Corporation'),
    ('fdf0', 'Google'),
    ('fdf3', 'Amazon Lab126'),
    ('fe1f', 'Garmin International, Inc.'),
    ('fe25', 'Apple, Inc.'),
    ('fe2c', 'Google Fast Pair (legacy)'),
    ('fe33', 'Chipolo (secondary)'),
    ('fe40', 'Anhui Huami (Mi Band)'),
    ('fe61', 'Logitech International SA'),
    ('fe65', 'Chipolo d.o.o.'),
    ('fe9f', 'Google Cast / Nest'),
    ('fea0', 'Google'),
    ('feaa', 'Eddystone (Google)'),
    ('feac', 'Nokia'),
    ('feb2', 'Microsoft Corporation'),
    ('febf', 'Nest Labs Inc.'),
    ('fed3', 'Apple, Inc.'),
    ('fed4', 'Apple, Inc.'),
    ('fed8', 'Google'),
    ('feda', 'Google'),
    ('fedd', 'Jawbone'),
    ('fede', 'Coin, Inc.'),
    ('feed', 'Tile, Inc.'),
    ('feee', 'Polar Electro Oy'),
    ('fef3', 'Google Fast Pair'),
    -- Custom 128-bit UUIDs identified empirically from captures (stored
    -- without dashes, lowercase, to match how DuckDB renders the column)
    ('61ce1c20e8bc428791fd7cc25f0df500', '(unidentified — broadcasts with 0x180a, persistent in-house)'),
    ('3e1d50cd7e3e427d8e1cb78aa87fe624', 'Amazon Fire TV remote (Style B)'),
    ('feff', 'GN ReSound A/S')
) AS t(uuid, vendor_name);
